fix cpca copy error exit

diff --git a/cpca2 b/cpca2
--- a/cpca2
+++ b/cpca2
@@ -36,6 +36,10 @@ do
     fi
     supervisorctl  start all
     rsync  -P --size-only --remove-source-files  ${file}  ${target_dir}
+    if [ $? != 0 ] ;then
+       echo "rsync copy error,target maybe full -> ${file}"
+       break
+    fi
     delete_locked_file $file
 done
 
